aws/aws-encryption-sdk-python

setup.py

When attrs package update to version 17 some things may have broken.
In my case i got an exception in python set object when you try to add a new element to the list and the object is not hashable
internal/utils.py line 174 raise TypeError
encrypted_data_keys.add(encrypted_key)

fix: TypeError "unhashable type: "EncryptedDataKey"

---

.travis.yml
README.rst
examples/test/test_i_basic_encryption.py
examples/test/test_i_basic_file_encryption_with_multiple_providers.py
examples/test/test_i_data_key_caching_basic.py
test/integration/README
test/integration/README.rst
test/integration/integration_test_utils.py
test/integration/test_values_template.conf
tox.ini

Adding Travis CI config, adding badges to readme, and updating integration test configuration methodology from config file to environment variables (primarily to simplify in running integration tests in Travis).

Adding Travis CI config

---

src/aws_encryption_sdk/identifiers.py
test/unit/test_identifiers.py

This is an idea I've been playing with to try and make the algorithm suites more comprehensible and less error-prone.
Each algorithm suite is composed of a large number of individual values that together form the complete algorithm suite specification.
These algorithm suite definitions are hard to understand, hard to debug, and easy to mess up.
Algorithm suites are not conceptually a grouping of a large number of primitives. They are a grouping of a small number of groupings of related values. Each of these groupings define characteristics of the overall algorithm suite.
I have separated these out into three sub-suites:
1. Encryption : contains only those values that control the encryption behavior
1. KDF : contains only those values that control the key derivation behavior
1. …

refactoring Algorithm definition components into separate encryption, kdf, and authentication algorithm suites

---

requirements.txt
src/aws_encryption_sdk/key_providers/base.py
src/aws_encryption_sdk/key_providers/kms.py
src/aws_encryption_sdk/key_providers/raw.py
src/aws_encryption_sdk/materials_managers/caching.py
src/aws_encryption_sdk/streaming_client.py
src/aws_encryption_sdk/structures.py
tox.ini

* updating attr to >=17.4.0 and changing all uses of attr.ib from deprecated "convert" to "converter" #39 
* updating pytest to >=3.3.1 to move past #32

updating attr to >=17.4.0 and changing all uses of attr.ib from deprecated "convert" to "converter"

---

README.rst
appveyor.yml
examples/test/test_i_basic_file_encryption_with_multiple_providers.py
examples/test/test_i_basic_file_encryption_with_raw_key_provider.py

Adding AppVeyor build configuration and badge #20 . Also fixes a minor issue with some of the examples tests that broke when run on Windows.
The AppVeyor project for this repo is set up[1], but because we can't use the OAuth integration it won't actually build properly until the `appveyor.yml` file is in this `master` branch. Here's the build on my fork[2].
[1] https://ci.appveyor.com/project/mattsb42-aws/aws-encryption-sdk-python-m2mgl
[2] https://ci.appveyor.com/project/mattsb42-aws/aws-encryption-sdk-python/build/1.0.5

adding AppVeyor build configuration and badge

---

.travis.yml
test/integration/integration_test_utils.py
test/integration/test_i_thread_safety.py
test/integration/test_i_xcompat_kms.py
test/requirements.txt
tox.ini

Seeing this[1], I realized two things:
1. It is not currently very easy to run our tests outside of tox.
1. Some of our integration tests look for the CMK ARN environment variable during setup rather than execution. This can cause problems when attempting to run non-integ tests using pytest markers because the setup code is run whether you want those markers or not.
This change fixes both of these issues.
[1] https://github.com/pyca/cryptography/blob/master/Jenkinsfile#L151-L165

Make the experience running tests outside of tox friendlier

---

src/aws_encryption_sdk/identifiers.py
src/aws_encryption_sdk/internal/utils/__init__.py
src/aws_encryption_sdk/key_providers/kms.py
test/integration/test_i_aws_encrytion_sdk_client.py
test/unit/test_providers_kms_master_key.py
test/unit/test_providers_kms_master_key_provider.py
test/unit/test_utils.py

*Issue #, if available:* #25
* Simplify the user agent to just identify the client in general, not any specific MKP.
* Use the correct method of setting the user agent for new clients.
* Add default client building logic for `KMSMasterKey` to both simplify direct use of the class and make it more likely that any given client is using our user agent.
* Actually test to make sure that the user agent is really being modified.

Partial fix (and actually test for) user agent modification

---

CHANGELOG.rst
doc/index.rst
src/aws_encryption_sdk/identifiers.py

* Version bump and changelog for v1.3.4
* Remove redundant title in docs index. The same title is in CHANGELOG.rst, so this created a double title: http://aws-encryption-sdk-python.readthedocs.io/en/latest/#changelog
* Add release dates for versions in changelog. This will make it easier for us to keep the changelog up to date as changes are made in between releases and make it clearer to readers whether we have actually released features yet.

1.3.4 version bump and changelog

---

.travis.yml
examples/src/pylintrc
src/aws_encryption_sdk/identifiers.py
src/aws_encryption_sdk/internal/formatting/deserialize.py
src/aws_encryption_sdk/internal/utils/__init__.py
src/aws_encryption_sdk/streaming_client.py
src/pylintrc
test/pylintrc
test/unit/test_caches.py
test/unit/test_deserialize.py

*Issue #, if available:* #65 #17 #49 
In the process of updating our code to comply with the new checks in Pylint 2.0.0, I made the additional changes:
- Finally got around to breaking `deserialize_header` logic out into component functions.
- Above enabled turning on flake8 and pylint runs in Travis.
- Turned on bandit run in Travis. 1.4.1 (or whatever the next version will be) still is not published, but we're pulling from their GitHub head for now.

Pylint 2.0.0 and a little bit of housekeeping

---

CHANGELOG.rst
src/aws_encryption_sdk/identifiers.py
src/aws_encryption_sdk/streaming_client.py
test/functional/test_f_aws_encryption_sdk_client.py

*Issue #, if available:* #73 
`StreamEncryptor` and `StreamDecryptor` should always report as readable if they are open.
We had previously been inheriting this from `io.BaseIO`, but it turns out that this was not implementing the behavior we expected.

Fix stream handler implementation of readable()

---

CHANGELOG.rst
src/aws_encryption_sdk/internal/utils/__init__.py
test/unit/test_utils.py

*Issue #, if available:* #75 
Previously, we would only allow strings, bytes, `BytesIO`, `StringIO`, and `file` sources. This leaves out a lot of streams that look and feel close enough for what we need.
I would like to eventually properly define "this is the API that source streams must provide", but that will require more serious thought to avoid breaking people if we decide later that needs to change.

allow duck-typing of source streams

---

CHANGELOG.rst
src/aws_encryption_sdk/identifiers.py
src/aws_encryption_sdk/key_providers/kms.py
test/unit/test_providers_kms_master_key_provider.py

*Issue #, if available:* #83
Fix KMSMasterKeyProvider to determine the default region before trying to create the requested master keys.
We were previously trying to build the master keys *before* finding the default region, which would break any time a requested key ID was not a full Arn.

fix KMSMasterKeyProvider to determine the default region before trying to create the requested master keys

---

src/aws_encryption_sdk/key_providers/kms.py
test/integration/test_i_aws_encrytion_sdk_client.py

This is needed to remove the client from the regional client cache if a error
is detected that indicates the client has been misconfigured.
If this approach is allowed, I'll add unit tests.

Proxy KMS Client to catch BotoCoreErrors

---

decrypt_oracle/tox.ini
test_vector_handlers/tox.ini
tox.ini

Lock onto bandit>=1.5.1 now that PyQCA is doing releases!

---

test_vector_handlers/src/awses_test_vectors/manifests/full_message/encrypt.py
test_vector_handlers/test/integration/commands/test_i_full_message_encrypt.py

*Issue #, if available:* https://github.com/awslabs/aws-encryption-sdk-test-vectors/issues/7
This standardizes the entry-point manifest to the `manifest.json` name. Once we have the meta-manifest compatibility built, I would prefer to change the entry-point to always be a meta-manifest, but anything reading a manifest must be able to identify its type regardless.

standardize on manifest.json as the entry-point manifest for test vectors

---

CHANGELOG.rst
src/aws_encryption_sdk/identifiers.py
test/functional/test_f_aws_encryption_sdk_client.py
test/functional/test_f_xcompat.py

*Issue #, if available:* #56 
Adds support for SHA384 and SHA512 for use with RSA OAEP wrapping algorithms and tests for same.

Add support for SHA384 and SHA512 for use with RSA OAEP wrapping algorithms

---

tox.ini

I recently ran across [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear), and it seemed like a good thing to add to our linting checks. Turns out we're already compliant with all the checks, but it's another good set of guidelines to stick to.

add flake8-bugbear to flake8 check

---

src/aws_encryption_sdk/streaming_client.py
test/unit/test_streaming_client_encryption_stream.py
tox.ini

*Issue #, if available:* #26 
The actual fix was tiny. Most of this PR is refactoring the test class from unittest to pytest.

Properly handle negative values to _EncryptionStream.read()

---

CHANGELOG.rst
setup.cfg
src/aws_encryption_sdk/internal/utils/__init__.py
src/aws_encryption_sdk/internal/utils/streams.py
src/aws_encryption_sdk/streaming_client.py
test/functional/test_f_aws_encryption_sdk_client.py
test/unit/test_streaming_client_encryption_stream.py
test/unit/test_streaming_client_stream_decryptor.py
test/unit/test_streaming_client_stream_encryptor.py
test/unit/test_util_streams.py
test/unit/test_utils.py
test/unit/unit_test_utils.py

*Issue #, if available:* #24 
As noted in #24, the `streaming_client` classes have not historically correctly handled partial reads. Rather than accepting reads from the source stream that return fewer than the requested number of bytes, they assumed that this meant the source stream was complete. Per PEP 3116, this is incorrect: the stream should not be considered complete until no bytes are returned.
In order to simplify logic everywhere else, I ended up just adding a `ProxyObject` wrapper that keeps hitting the wrapped stream on read until it either gets the requested number of bytes or hits the end of the wrapped stream (as indicated by the stream returning nothing).
Tightly coupled with this was updating the fix made in #98 to correctly normalize to the …

Fix handling of partial reads

---

CHANGELOG.rst
src/aws_encryption_sdk/identifiers.py
src/aws_encryption_sdk/streaming_client.py
test/functional/test_f_aws_encryption_sdk_client.py

Remove debug logging that may contain input data when encrypting non-default unframed messages.

fix logging issue

---

src/aws_encryption_sdk/internal/formatting/deserialize.py
src/aws_encryption_sdk/internal/formatting/encryption_context.py
src/aws_encryption_sdk/streaming_client.py
src/aws_encryption_sdk/structures.py
test/functional/test_f_aws_encryption_sdk_client.py
test/unit/test_structures.py

* Clean up some logging calls to avoid type mismatch.
* Remove data key from container repr values

Log cleanup

---

src/aws_encryption_sdk/internal/formatting/deserialize.py
src/aws_encryption_sdk/streaming_client.py
test/functional/test_f_aws_encryption_sdk_client.py
test/unit/test_deserialize.py
test/unit/test_streaming_client_encryption_stream.py
test/unit/test_streaming_client_stream_decryptor.py
test/unit/test_utils.py
test/unit/unit_test_utils.py

This is the first in a series of changes to implement #103.
This removes the need for the source stream to implement `tell()` on the decrypt path.

Remove requirement for tell() on decrypt

---

src/aws_encryption_sdk/internal/formatting/deserialize.py
src/aws_encryption_sdk/streaming_client.py
test/unit/test_streaming_client_stream_decryptor.py
test/unit/test_streaming_client_stream_encryptor.py

* Expand imports to improve readability
* Remove internal function that was deprecated in #104 

Expand imports to improve readability

---

src/aws_encryption_sdk/streaming_client.py
test/functional/test_f_aws_encryption_sdk_client.py
test/unit/test_streaming_client_stream_encryptor.py

Remove the requirement for `source_stream.tell()`.

Remove requirement for tell() on source_stream

---

src/aws_encryption_sdk/streaming_client.py
test/functional/test_f_aws_encryption_sdk_client.py
test/unit/test_streaming_client_stream_decryptor.py
test/unit/test_streaming_client_stream_encryptor.py

Remove need for `source_stream` to implement `closed`.

Remove need for source_stream.closed

---

test/integration/test_i_aws_encrytion_sdk_client.py

*Issue #, if available:* #99 
Migrated "test/integration/test_i_aws_encrytion_sdk_client.py" from unittest to pytest

Migrate test_i_aws_encryption_sdk_client.py from unittet to pytest

---

src/aws_encryption_sdk/streaming_client.py
test/functional/test_f_aws_encryption_sdk_client.py
test/unit/test_streaming_client_stream_decryptor.py
test/unit/test_streaming_client_stream_encryptor.py

Removes need for `source_stream` to implement `close()`.
This does have the effect that we would previously close the source stream when it was empty and we now will not. I'm on the fence about whether this constitutes a change that needs a `Y` version change. Thoughts?

remove now unnecessary use of source_stream.close()

---

decrypt_oracle/.chalice/buildspec.yaml
decrypt_oracle/.chalice/pipeline.py
decrypt_oracle/setup.cfg
decrypt_oracle/tox.ini

This adds the necessary tooling to get the decrypt oracle continuous deployment infrastructure set up. I have tested this in my account and it works as expected. The decrypt oracle is currently deployed to `https://chuy714fq0.execute-api.us-west-2.amazonaws.com/api`.
* `decrypt_oracle/.chalice/pipeline.py` constructs a CloudFormation template and deploys/updates the stack for the CD pipeline. Currently, this will need to be run manually, but a next step on this would be to expand the pipeline to keep itself updated.
* `decrypt_oracle/.chalice/buildspec.yaml` is the buildspec that is used by the CodeBuild stage in the pipeline to build the new version of the decrypt oracle.
By submitting this pull request, I confirm that my contribution is made under the terms of …

Decrypt Oracle deployment tooling

---

test/unit/test_streaming_client_stream_encryptor.py

*Issue #, if available:* #99
Migrated "test/unit/test_streaming_client_stream_encryptor.py" from unittest to pytest

Migrate unit/test_streaming_client_stream_encryptor.py from unittest to pytest

---

test/unit/test_defaults.py
test/unit/test_providers_base_master_key.py

*Issue #, if available:* #99 
Migrated "test/unit/test_providers_base_master_key.py" from unittest to pytest

Migrate "test/unit/test_providers_base_master_key.py" from unittest to pytest

---

test/unit/test_encryption_context.py

*Issue #, if available:* #99
Migrated "test/unit/test_encryption_context.py" from unittest to pytest

Migrate unit/test_encryption_context.py from unittest to pytest

---

test/unit/test_deserialize.py

*Issue #, if available:* #99 
Migrated "test/unit/test_deserialize.py" from unittest to pytest

Migrate unit/test_deserialize.py from unittest from pytest

---

test/unit/test_deserialize.py
test/unit/test_providers_kms_master_key.py

*Issue #, if available:* #99
Migrated "test/unit/test_providers_kms_master_key.py" from unittest to pytest

Migrate "test/unit/test_providers_kms_master_key.py" from unittest to pytest

---

test/unit/test_utils.py

*Issue #, if available:* #99
Migrated "test/unit/test_utils.py" from unittest to pytest

Migrate unit/test_utils.py from unittest to pytest

---

decrypt_oracle/src/pylintrc
examples/src/pylintrc
examples/test/pylintrc
src/pylintrc
test/pylintrc
test_vector_handlers/src/pylintrc

Convert pylintrc files from short IDs to readable names

Convert pylintrc files from short IDs to readable names

---

src/aws_encryption_sdk/caches/local.py
src/aws_encryption_sdk/caches/null.py
src/aws_encryption_sdk/materials_managers/caching.py
src/aws_encryption_sdk/materials_managers/default.py

Looks like `isort`'s handling of relative imports changed slightly.
This is just re-applying `autoformat` to catch these changes.

apply updated isort processing

---

CHANGELOG.rst
src/aws_encryption_sdk/key_providers/base.py
test/functional/key_providers/__init__.py
test/functional/key_providers/test_base.py

*Issue #, if available:* #150
`MasterKeyprovider.decrypt_data_key_from_list` should catch expected exceptions from both `MasterKeyProvider.decrypt_data_key` and `MasterKey.decrypt_data_key` #150

Fix MasterKeyprovider.decrypt_data_key_from_list error handling

---

CHANGELOG.rst
src/aws_encryption_sdk/identifiers.py
src/aws_encryption_sdk/streaming_client.py
test/functional/test_f_aws_encryption_sdk_client.py
test/unit/test_streaming_client_stream_decryptor.py

Prepping for a `1.4.0` release today.

bump version to 1.4.0 and update changelog

---

examples/__init__.py
examples/test/examples_test_utils.py
examples/test/pylintrc
examples/test/test_i_basic_encryption.py
examples/test/test_i_basic_file_encryption_with_multiple_providers.py
examples/test/test_i_basic_file_encryption_with_raw_key_provider.py

In preparation for #156, I realized that I hadn't given these examples tests the same treatment that I gave the DDB encryption client and Pipeformer.
These changes make writing tests for examples much simpler and less finicky.

reorganize examples cross-imports to simplify tests

---

decrypt_oracle/tox.ini
src/aws_encryption_sdk/materials_managers/caching.py
test/unit/test_material_managers_caching.py
tox.ini

Issue #147 
Added a check for max_age being greater than 0 and added an appropriate error message.

Added a check for max_age being greater than 0

---

test/unit/test_providers_kms_master_key_provider.py

This fixes issue #31, in which users who have configured a default AWS region (either via ~/.aws/config or via environment variable) will experience failing tests for `KMSMasterKeyProvider`. I tried to keep the tests mostly unchanged, but in some cases I elected to simply skip them since the test didn't provide much value if there was already a default value configured. 

Fixed KMS master key provider tests when default AWS region is configured

---

src/aws_encryption_sdk/key_providers/kms.py
test/integration/integration_test_utils.py
test/integration/test_i_aws_encrytion_sdk_client.py
test/unit/test_providers_kms_master_key_provider.py

*Issue #190 *
*Description of the change is inside the issue + added a test for this issue:*

[issue-190] Regional clients modify default botocore session

---

src/aws_encryption_sdk/key_providers/base.py

As part of building the master key provider keyring, I realized that I needed to be able to get the master key object that decrypted a data key. This is important because we need the key name (ie, key ID) for the keyring trace, but decrypted data key instead contains the provider info. Usually this is fine, but for example in the case of the raw AES master key, they are not the same.
`MasterKeyProvider.master_keys_for_data_key` gives us this capability by exposing the master key discovery in the public API for this parent class.
In the process of creating `master_keys_for_data_key`, I realized that I could drastically simplify `MasterKeyProvider.decrypt_data_key` by using the new `master_keys_for_data_key` method.
Also, I collapsed the logic of …

Refactor MasterKeyProvider.master_keys_for_data_key

---

tox.ini

fixes #173 
update flake8-docstrings to minimum version of 1.5.0 to address compatibility issues with pydocstyle 4.x

update flake8-docstrings to minimum version of 1.5.0

---

doc/conf.py
doc/index.rst
src/aws_encryption_sdk/__init__.py
src/aws_encryption_sdk/exceptions.py
src/aws_encryption_sdk/keyrings/base.py
src/aws_encryption_sdk/keyrings/multi.py
src/aws_encryption_sdk/keyrings/raw.py
src/aws_encryption_sdk/materials_managers/__init__.py
src/aws_encryption_sdk/materials_managers/caching.py
src/aws_encryption_sdk/materials_managers/default.py
src/aws_encryption_sdk/streaming_client.py
test/functional/test_client.py
test/integration/test_client.py
test/unit/materials_managers/test_caching.py
test/unit/materials_managers/test_default.py
test/unit/unit_test_utils.py

*Issue #, if available:* #211 
This adds support for using keyrings to `DefaultCryptographicMaterialsManager` as well as the appropriate passthroughs via `CachingCryptographicMaterialsManager` and the encrypt/decrypt entry points.

feat: enable use of keyrings

---

CHANGELOG.rst
src/aws_encryption_sdk/__init__.py
src/aws_encryption_sdk/materials_managers/__init__.py
src/aws_encryption_sdk/streaming_client.py
src/aws_encryption_sdk/structures.py
test/functional/test_client.py
test/unit/test_client.py
test/unit/test_structures.py

resolves: #223 
After discussing #223 with @WesleyRosenblum and @acioc, we agreed that going with option 2 made the most sense and did not introduce notable risk of breaking customers. The fact that none of the tests (aside from an over-mocked unit test) needed to be changed after I changed the return values supports this conclusion.
There are two main changes introduced here, both with the aim of making the keyring trace accessible to callers:
1. The streaming classes now set a `keyring_trace` attribute as soon as they have the encryption/decryption materials.
1. The one-step APIs now return the new `CryptoResult` rather than a tuple. `CryptoResult` gives us the flexibility to add more output values in the future while also allowing …

Expose keyring trace in results

---

src/aws_encryption_sdk/keyrings/aws_kms/__init__.py
test/unit/keyrings/test_aws_kms.py

resolves #227 
Reasoning is described in #227 and https://github.com/awslabs/aws-encryption-sdk-specification/issues/84.
The short version is that rather than discovery being a derived property that is the result of an absence of key IDs, discovery is now an explicit parameter that is incompatible with key IDs being supplied.

feat: change KMS discovery keyring configuration path

---

src/aws_encryption_sdk/internal/formatting/serialize.py
src/aws_encryption_sdk/keyrings/aws_kms/__init__.py
src/aws_encryption_sdk/keyrings/multi.py
src/aws_encryption_sdk/keyrings/raw.py
src/aws_encryption_sdk/materials_managers/__init__.py
src/aws_encryption_sdk/structures.py
test/functional/keyrings/aws_kms/test_aws_kms.py
test/unit/internal/formatting/test_serialize.py
test/unit/keyrings/raw/test_raw_aes.py
test/unit/keyrings/raw/test_raw_rsa.py
test/unit/keyrings/test_multi.py
test/unit/materials_managers/test_material_managers.py
test/unit/unit_test_utils.py

* resolves: #214 
* https://github.com/awslabs/aws-encryption-sdk-specification/issues/32
The primary focus of this change is to move keyrings to immutable cryptographic materials. Rather than providing APIs that let you modify materials, we now provide APIs that let you get a new copy of those materials that also include additional contents.
While I was working on that, I found a few other points where the keyrings were not compliant with the spec, particularly around behavior when failing on encrypt and decrypt, and in the specific values set in the keyring trace. Looking back through the changes, I would have a hard time extracting any single piece, so unfortunately they're all just getting lumped into this one PR.
By submitting this …

feat: immutable cryptographic materials (for keyrings)

---

src/aws_encryption_sdk/keyrings/aws_kms/__init__.py
test/functional/keyrings/aws_kms/test_aws_kms.py

In order for anyone to reasonably check the keyring trace, they need to be able to access the key namespace value for the KMS keyring. This exposes that for access.

fix: expose the KMS keyring key namespace value for public access

---

src/aws_encryption_sdk/keyrings/aws_kms/__init__.py
src/aws_encryption_sdk/keyrings/raw.py
src/aws_encryption_sdk/structures.py

Fixing some minor issues that I noticed while prepping #234 .

docs: fix sphinx formatting and syntax

---

examples/README.md
examples/src/master_key_provider/__init__.py
examples/src/master_key_provider/aws_kms/__init__.py
examples/src/master_key_provider/aws_kms/discovery_decrypt.py
examples/src/master_key_provider/aws_kms/multiple_regions.py
examples/src/master_key_provider/aws_kms/single_cmk.py
examples/src/master_key_provider/multi/__init__.py
examples/src/master_key_provider/multi/aws_kms_with_escrow.py
examples/src/master_key_provider/raw_aes/__init__.py
examples/src/master_key_provider/raw_aes/raw_aes.py
examples/src/master_key_provider/raw_rsa/__init__.py
examples/src/master_key_provider/raw_rsa/private_key_only_from_pem.py

#213
#146
To aid in migration efforts, these examples show the basics of how to use master key providers in the new example format.

docs: add master key provider examples

---

examples/src/keyring/aws_kms/multiple_regions.py
src/aws_encryption_sdk/keyrings/aws_kms/__init__.py
test/functional/keyrings/aws_kms/test_aws_kms.py
test/integration/integration_test_utils.py
test/unit/keyrings/test_aws_kms.py

fix: correct KMS keyring parameter name from child_key_ids to key_ids

---

.github/workflows/ci_test-vector-handler.yaml

I had been attempting to have the test vector handler tests only run on push and scheduled events, but that doesn't appear to have been working as expected. For now, this will just completely disable those tests. This is a housekeeping effort to avoid the current state where every PR has ~57 checks that are expected to fail.
Three of the static analysis checks are still expected to fail, but I think that handling those is more manageable and IMO it is better to let them keep failing until we can clean that up than to disable them. Having them fail reminds us that we need to fix them.
NOTE: These tests are still running as part of the Travis suite. We cannot run them in GitHub Actions until we figure out a solution to getting AWS credentials into GitHub Actions on …

chore: disable the test vector handler tests in GitHub Actions

---

CHANGELOG.rst
README.rst
src/aws_encryption_sdk/__init__.py
src/aws_encryption_sdk/key_providers/base.py
src/aws_encryption_sdk/key_providers/kms.py
src/aws_encryption_sdk/key_providers/raw.py
test/unit/key_providers/base/test_base_master_key_provider.py

resolves: #238 
I went with `DeprecationWarning` even though it is ignored by default because we do not have any plans for when we will actually remove master key providers. When that changes, we should up that to a `UserWarning` and communicate the upcoming removal as defined in our versioning policy.
https://docs.python.org/3/library/warnings.html#warning-categories
In addition to adding deprecation notices, this also removes any use of master key providers from inline examples. For the readme I decided to just remove all of the inline examples because we have a much more comprehensive set of examples in the examples directory now. The new concepts descriptions in the readme are taken from developer guide's concepts section. …

feat: deprecate master key providers

---

README.rst

The relative link worked when viewing the readme on GitHub, but didn't work in the sphinx-rendered docs.
https://aws-encryption-sdk-python.readthedocs.io/en/keyring/

docs: fix security issue notifications link in readme

---

examples/src/keyring/raw_aes/raw_aes.py
src/aws_encryption_sdk/keyrings/raw.py
test/functional/keyrings/raw/test_raw_aes.py
test/functional/keyrings/test_multi.py
test/unit/keyrings/raw/test_raw_aes.py
test/unit/keyrings/raw/test_raw_rsa.py
test/unit/keyrings/test_multi.py
test/unit/unit_test_utils.py

resolves: #246
This implements proposed solution number 2 detailed in #246, removing wrapping algorithm as an input parameter, restricting wrapping key material length to supported lengths, and deriving the wrapping algorithm suite from the wrapping key material length.

feat: remove wrapping_algorithm input parameter from RawAESKeyring

---

test/integration/test_client.py
tox.ini

related to: https://github.com/pyca/cryptography/pull/5197
In a recent batch of test refactoring, I inadvertently moved some calls that relied on integ test environment setup (namely: setting certain environment variables) into the test setup that used to be within the test body. This caused these calls to be made during pytest test discovery. This is a problem because we use pytest markers to categorize our tests and test discovery must complete before markers can be applied to filter tests to run.
We have a test (`TOXENV=nocmk`) that should have caught this, but it looks like it was no longer removing the environment variable restrictions. That is fixed now, along with a comment explaining why that is important.
By submitting this pull …

fix: move calls requiring integ test environment setup from test setup to inside test body

---

examples/README.md
examples/src/keyring/raw_rsa/keypair.py
examples/src/keyring/raw_rsa/keypair_from_pem.py
src/aws_encryption_sdk/keyrings/raw.py
test/functional/keyrings/raw/test_raw_rsa.py
test/functional/keyrings/test_multi.py
test/unit/keyrings/raw/test_raw_rsa.py
test/unit/unit_test_utils.py

resolves: #257
Changes as determined in #257.

feat: refactor raw RSA keyrings configuration per #257

---

examples/README.md
examples/src/keyring/aws_kms/act_like_aws_kms_master_key_provider.py
examples/src/keyring/aws_kms/discovery_decrypt.py
examples/src/keyring/aws_kms/discovery_decrypt_in_region_only.py
examples/src/keyring/aws_kms/discovery_decrypt_with_preferred_regions.py

resolves: #248 
In addition to using the configured AWS KMS CMKs, the AWS KMS master key provider attempts to decrypt any data keys that were encrypted under an AWS KMS CMK. This behavior is not always obvious, and when we designed the AWS KMS keyring, we decided that it was best to separate these behaviors, but as customers migrate from master key providers to keyrings, it will be helpful to have an example of how to replicate the exact behavior of the AWS KMS master key provider using keyrings.

docs: add example to replicate AWS KMS MKP behavior with AWS KMS keyring

---

examples/src/keyring/aws_kms/act_like_aws_kms_master_key_provider.py

Fixing a typo that I found while reviewing https://github.com/aws/aws-encryption-sdk-java/pull/178

docs: fix typo in example comments

---

test_vector_handlers/src/awses_test_vectors/__init__.py
test_vector_handlers/src/awses_test_vectors/commands/__init__.py
test_vector_handlers/src/awses_test_vectors/commands/full_message_decrypt.py
test_vector_handlers/src/awses_test_vectors/commands/full_message_encrypt.py
test_vector_handlers/src/awses_test_vectors/internal/__init__.py
test_vector_handlers/src/awses_test_vectors/internal/aws_kms.py
test_vector_handlers/src/awses_test_vectors/internal/defaults.py
test_vector_handlers/src/awses_test_vectors/internal/mypy_types.py
test_vector_handlers/src/awses_test_vectors/internal/util.py
test_vector_handlers/src/awses_test_vectors/manifests/__init__.py
test_vector_handlers/src/awses_test_vectors/manifests/full_message/__init__.py
test_vector_handlers/src/awses_test_vectors/manifests/full_message/decrypt.py
test_vector_handlers/src/awses_test_vectors/manifests/keys.py
test_vector_handlers/src/pylintrc
test_vector_handlers/test/pylintrc
test_vector_handlers/tox.ini

This cleans up some outstanding issues with the test vector handler static analysis checks that have been sitting around since they were written. I originally had these checks disabled in Travis with a plan to come back and fix and enable them later, but later never came. When I moved those checks over to GitHub Actions I decided to enable them as a reminder to actually fix them. This change addresses the issue and will let us lock down our remaining CI checks as required.

chore: clean up and fix test vector handler static analysis checks

---

src/aws_encryption_sdk/internal/validators.py
test_vector_handlers/src/awses_test_vectors/manifests/full_message/decrypt.py

`pylint` 2.5.0 landed yesterday and it looks like its unused argument rules changed slightly.

chore: update pylint settings to match changes in 2.5.0

---

src/aws_encryption_sdk/__init__.py
test/unit/test_client.py

resolves: #44 
- Avoided hanging object references in helper functions -
* Created a deep copy of header and keyring trace objects from the managed stream before passing them to `CryptoResult` in the `encrypt`[1] and `decrypt`[2] functions.
* Modified the test for checking equality of header but not identity
[1] https://github.com/aws/aws-encryption-sdk-python/blob/82e21567a7111aea99a364e19842c3fa87a081bb/src/aws_encryption_sdk/__init__.py#L84-L87
[2] https://github.com/aws/aws-encryption-sdk-python/blob/82e21567a7111aea99a364e19842c3fa87a081bb/src/aws_encryption_sdk/__init__.py#L143-L146

hanging object references in helper functions avoided

---

examples/README.md

In going through to enumerate the examples for https://github.com/awslabs/aws-encryption-sdk-specification/issues/103, I realized that the client supplier examples were not linked.

docs: add links to custom AWS KMS client configuration examples in examples readme

---

src/aws_encryption_sdk/keyrings/aws_kms/__init__.py
src/aws_encryption_sdk/keyrings/raw.py
test/functional/keyrings/raw/test_raw_aes.py
test/functional/keyrings/raw/test_raw_rsa.py

*Issue #, if available:* #279 
*Description of changes:* 
Implement spec changed introduced in https://github.com/awslabs/aws-encryption-sdk-specification/pull/140. Initialization now throws in both raw keyrings is `key_namespace` equals `"aws-kms"`.

fix(raw-keyrings): Raise when passed a key_namespace of "aws-kms"

---

src/aws_encryption_sdk/__init__.py
src/aws_encryption_sdk/exceptions.py
src/aws_encryption_sdk/identifiers.py
src/aws_encryption_sdk/keyrings/aws_kms/__init__.py
src/aws_encryption_sdk/keyrings/raw.py
src/aws_encryption_sdk/materials_managers/__init__.py
src/aws_encryption_sdk/streaming_client.py
src/aws_encryption_sdk/structures.py
test/functional/keyrings/aws_kms/test_aws_kms.py
test/functional/keyrings/raw/test_raw_aes.py
test/functional/keyrings/raw/test_raw_rsa.py
test/functional/keyrings/test_multi.py
test/functional/test_client.py
test/unit/caches/test_local.py
test/unit/keyrings/raw/test_raw_aes.py
test/unit/keyrings/raw/test_raw_rsa.py
test/unit/materials_managers/test_material_managers.py
test/unit/test_structures.py
test/unit/unit_test_utils.py

*Issue #, if available:* resolves #272 
*Description of changes:* 
* Remove the keyring trace
* Update version comments where I came across them (pursuant to #290)
*Note:* Some tests were removed, or had some assert statements removed. Coverage is unchanged.

refactor: Remove keyring trace

---

decrypt_oracle/.chalice/pipeline.py
decrypt_oracle/src/aws_encryption_sdk_decrypt_oracle/key_providers/counting.py
decrypt_oracle/src/aws_encryption_sdk_decrypt_oracle/key_providers/null.py
decrypt_oracle/src/pylintrc
decrypt_oracle/test/integration/integration_test_utils.py
src/pylintrc
test/pylintrc
test_vector_handlers/src/pylintrc
test_vector_handlers/test/pylintrc

Recent versions of Pylint added some new checks that recommend using syntax that was introduced in Python 3. This required two changes on our part:
1. The decrypt oracle is Python 3 only. There, I actually made the recommended changes (and re-enabled a similar check that was incorrectly disabled.)
1. Everywhere else, disable the new checks.

chore: apply changes to accomodate updated Pylint checks

---

decrypt_oracle/.chalice/pipeline.py
decrypt_oracle/src/aws_encryption_sdk_decrypt_oracle/key_providers/counting.py
decrypt_oracle/src/aws_encryption_sdk_decrypt_oracle/key_providers/null.py
decrypt_oracle/src/pylintrc
decrypt_oracle/test/integration/integration_test_utils.py
src/pylintrc
test/pylintrc
test_vector_handlers/src/pylintrc
test_vector_handlers/test/pylintrc

* chore: update pylintrc with new Python3-only checks
* chore: decrypt oracle is Python3-only
* chore: apply recommendations for Python 3 updates to super and error chaining

chore: apply changes to accomodate updated Pylint checks (#295)

---

tox.ini

This change shifts the twine configuration from depending entirely on `.pypirc` to be configured as expected to instead rely on `twine` and `pip` environment variable configuration.

chore: centralize twine configuration logic and remove dependency on pypirc

---

src/aws_encryption_sdk/__init__.py
test/unit/test_aws_encryption_sdk.py

* Fix a missing import, which would break existing customers
* New test fails without the fix in `__init__.py`, passes with the fix

Fix missing import from top level module

---

.travis.yml
CHANGELOG.rst
decrypt_oracle/src/aws_encryption_sdk_decrypt_oracle/app.py
decrypt_oracle/test/integration/integration_test_utils.py
decrypt_oracle/test/unit/key_providers/test_u_counting.py
decrypt_oracle/test/unit/key_providers/test_u_null.py
src/aws_encryption_sdk/streaming_client.py
test_vector_handlers/compatibility-requirements/1.7.1
test_vector_handlers/compatibility-requirements/2.0.0
test_vector_handlers/src/awses_test_vectors/internal/aws_kms.py
test_vector_handlers/src/awses_test_vectors/internal/mypy_types.py
test_vector_handlers/src/awses_test_vectors/internal/util.py
test_vector_handlers/src/awses_test_vectors/manifests/full_message/decrypt.py
test_vector_handlers/src/awses_test_vectors/manifests/full_message/encrypt.py
test_vector_handlers/src/awses_test_vectors/manifests/keys.py
test_vector_handlers/src/awses_test_vectors/manifests/master_key.py
test_vector_handlers/tox.ini
tox.ini

- Add `commitment_policy` where it was missing from a docstring
- Update test vectors to use new 2.0 symbols. Note that longer term we'll need to figure out a better story around testing multiple versions of code and multiple versions of ciphertext formats. For now, I've just used the newest symbols and updated the environments to only use ESDK versions 1.7.1 and 2.0.0.
- Update decrypt_oracle to use new 2.0 symbols.
- Update commit hashes in CHANGELOG
- Small updates to tox release environments

Post 2.0.0 fixes

---

.github/workflows/ci_decrypt-oracle.yaml
.github/workflows/ci_static-analysis.yaml
.github/workflows/ci_test-vector-handler.yaml
README.rst
decrypt_oracle/requirements-actual.txt
requirements.txt
test_vector_handlers/requirements.txt

Changes in 1.7.x depend on behavior introduced in cryptography 2.5, so we need to correctly model our dependency.
*Additional testing:*
If I set the requirement to `~=2.4.2` we see failures due to how cryptography checks byte types. If I set the requirement to `~=2.5.0`, it passes.

Update dependency on cryptography (1.7.x)

---

.github/workflows/ci_decrypt-oracle.yaml
.github/workflows/ci_static-analysis.yaml
.github/workflows/ci_test-vector-handler.yaml
README.rst
requirements.txt

Changes in 2.0.x depend on behavior introduced in cryptography 2.5, so we need to correctly model our dependency.
*Additional testing:*
If I set the requirement to `~=2.4.2` we see failures due to how cryptography checks byte types. If I set the requirement to `~=2.5.0`, it passes.

Update dependency on cryptography (2.x)

---

README.rst
src/aws_encryption_sdk/key_providers/kms.py
test_vector_handlers/compatibility-requirements/1.7.1
test_vector_handlers/compatibility-requirements/2.0.0

Be more explicit about the fact that, when using a StrictAwsKmsMasterKeyProvider, key aliases are not supported on decryption
*Issue #, if available:* https://github.com/aws/aws-encryption-sdk-python/issues/311

chore: Update README section on using StrictAwsKmsKeyProvider

---

.gitignore
buildspec.yml
codebuild/py27/awses_1.7.1.yml
codebuild/py27/awses_2.0.0.yml
codebuild/py27/awses_latest.yml
codebuild/py27/examples.yml
codebuild/py27/integ.yml
codebuild/py35/awses_1.7.1.yml
codebuild/py35/awses_2.0.0.yml
codebuild/py35/awses_latest.yml
codebuild/py35/examples.yml
codebuild/py35/integ.yml
codebuild/py36/awses_1.7.1.yml
codebuild/py36/awses_2.0.0.yml
codebuild/py36/awses_latest.yml
codebuild/py36/examples.yml
codebuild/py36/integ.yml
codebuild/py37/awses_1.7.1.yml
codebuild/py37/awses_2.0.0.yml
codebuild/py37/awses_latest.yml
codebuild/py37/examples.yml
codebuild/py37/integ.yml
codebuild/py38/awses_1.7.1.yml
codebuild/py38/awses_2.0.0.yml
codebuild/py38/awses_latest.yml
codebuild/py38/examples.yml
codebuild/py38/integ.yml
decrypt_oracle/tox.ini
test_vector_handlers/tox.ini
tox.ini

Adding buildspec to batch build
multiple Python runtimes
* Python 2.7
* Python 3.5
* Python 3.6
* Python 3.7
* Python 3.8

chore: Add AWS CodeBuild buildspec

---

README.rst
src/aws_encryption_sdk/key_providers/kms.py

*Issue #, if available:* 
*Description of changes:* We've seen some confusion over the point that you must only use key ARNs when decrypting with the Strict KMS MK Provider. Attempting to clarify that in the code and docs.

chore: Clarify StrictAwsKmsMasterKeyProvider docs

---

README.rst
requirements.txt

Now that we're passing key ids to KMS Decrypt operations, we need to make sure our boto version knows that Decrypt accepts KeyId as a parameter, otherwise client-side request validation fails. 
*Testing:*
Installed version 1.10 of boto3, confirmed that encrypt/decrypt operations succeed. Versions prior to 1.10 fail with `ParamValidationError: Unknown parameter in input: "KeyId", must be one of: CiphertextBlob, EncryptionContext, GrantTokens")`

chore: Update dependency on boto3

---

src/aws_encryption_sdk/internal/crypto/elliptic_curve.py
test/unit/test_streaming_client_encryption_stream.py

*Description of changes:* Marking pylint results as false positive.
It looks like the int_from_bytes pylint finding is related to the deprecation of int_from_bytes in cryptography 3.4. The code will still work, but will throw deprecation warnings. I'd like to mark this as a false positive now in order to keep CI clear while we determine how to best deal with that deprecation.
The reports from `test/unit/test_streaming_client_encryption_stream.py` also appear to be false positives. From static analysis it should be clear that MockEncryptingStream inherits from _EncryptionStream, which defines `next`: https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/streaming_client.py#L304
I think that how we define the `next` hook for Python3 may …

chore: Mark pylint false positive

---

codebuild/release/prod-release.yml
codebuild/release/test-release.yml

This is a step towards a more continuous release process. If this ends up being a productive path, we can expect to pull more validation into these codebuild specs.
*Testing*:
I've run CodeBuild builds against these specs and they succeed.

chore: Add 'release' buildspecs for codebuild

---

codebuild/release/prod-release.yml
test_vector_handlers/src/awses_test_vectors/manifests/full_message/decrypt.py
test_vector_handlers/src/awses_test_vectors/manifests/keys.py

Otherwise it just pulls down "latest", and with eventual consistency on PyPi
we might end up pulling down a previous version and not actually validating
our release.
This has the downside that, again due to eventual consistency, the new
version might not show up yet causing the build to fail. Since this build
is idempotent this is not the end of the world, but we may want to make
this more robust in the future.
*Testing*:
Confirmed that validation step fails if I provide a version that doesn't exist, and succeeds if I provide one that does exist.

chore: Explicitly override version when validating release

---

buildspec.yml
codebuild/coverage/coverage.yml
setup.cfg
tox.ini

Remove code coverage from base python command, add a dedicated code coverage environment, as well as code build specs to run it.
If we have all test environments running code coverage and configure it to fail on low coverage, we run into issues with things like integration tests, which intentionally are not exhaustive in their coverage. Plus running coverage on every test isn't that useful without a mechanism to do something about it (hoping a human happens to look at the output doesn't count).
So, make code coverage a dedicated target, have it target unit tests, and set a high threshold.
See also: https://github.com/aws/aws-dynamodb-encryption-python/pull/153
*Testing:*
Building gives me:
```
Required test coverage of 95.0% reached. Total coverage: 98.46%
```
If …

chore: Fail build if code coverage is too low

---

codebuild/release/prod-release.yml
codebuild/release/test-release.yml
codebuild/release/validate.yml

Now the test release validation does the same checks as the prod release (running the sample application against the new version), but targeting testpypi. To support this I've also refactored out the validation steps into a dedicated spec so both the prod and test specs can depend on it.
*Testing:*
Prod and test releases succeed (without any version uploaded, because it hasn't changed) when I give them the correct version and commit.
When I give a bad commit, we fail to checkout the branch and stop.
When I give a good commit but bad version, we detect that the authoritative version in `identifiers.py` does not match the requested version and stop.

chore: Add validation to test release codebuild spec

---

.github/workflows/ci_tests.yaml
buildspec.yml
codebuild/py39/awses_1.7.1.yml
codebuild/py39/awses_2.0.0.yml
codebuild/py39/awses_latest.yml
codebuild/py39/examples.yml
codebuild/py39/integ.yml
setup.py
tox.ini

Update setup.py and add 3.9 to CI (3.8 was already there)

chore: Add py38 and p39 to CI

---

src/aws_encryption_sdk/streaming_client.py

Address Issue aws#331 Typo in docstring for StreamDecryptor by correctly referring to the classes actions as decryption as compared to encryption.
*Issue #, if available:* #331
*Description of changes:* Replace incorrect encryption references with correct decryption references

Address Issue #331 Typo in docstring for StreamDecryptor

---

CHANGELOG.rst
src/aws_encryption_sdk/identifiers.py

Bump version in identifiers.py and update changelog

chore: Prepare for release 2.1.0

---

README.rst

We had a copy/paste error and were point at the CLI
*Testing:*
New link shows the right python version support: https://img.shields.io/pypi/pyversions/aws-encryption-sdk.svg

chore: Update README to correctly show supported python versions

---

decrypt_oracle/test/integration/integration_test_utils.py

The policy set earlier doesn’t exist in the 1.x branch. and this value should be perfectly equivalent since the decrypt oracle only decrypts.

fix: Downgrade decrypt oracle commitment policy

---

.readthedocs.yaml

This is primarily to add explicit ignoring of submodules, which have broken our doc builds: https://readthedocs.org/projects/aws-encryption-sdk-python/builds/13981651/
Note that we could also fix the specific error above by moving to the public test vectors module, but more generally this submodule is for testing and doesn't need to be included in documentation.
*Testing:*
Not really sure how to test this, since it relates to readthedocs integration.
My source material is:
https://sphinx-with-submodules.readthedocs.io/en/latest/ and https://docs.readthedocs.io/en/stable/config-file/v2.html#submodules 

chore: Add readthedocs config

---

.readthedocs.yaml

Recent build fails to import modules: https://readthedocs.org/projects/aws-encryption-sdk-python/builds/13990608/
I was able to reproduce locally by repeating the commands from the above, and it looks like some defaults are not set correctly for us. 
*Testing:*
When I simulate the commands from the above build, but add the commands to install requirements and local package, build succeeds.

chore: Further fixes to readthedocs config

---

decrypt_oracle/setup.py
setup.py
src/aws_encryption_sdk/internal/utils/streams.py
test/integration/test_kat_commitment.py
test/unit/test_caches_crypto_cache_entry.py
test/unit/test_caches_local.py
test/unit/test_crypto_authentication_signer.py
test/unit/test_crypto_authentication_verifier.py
test/unit/test_crypto_data_keys.py
test/unit/test_crypto_elliptic_curve.py
test/unit/test_crypto_encryption_decryptor.py
test/unit/test_crypto_encryption_encryptor.py
test/unit/test_crypto_prehashing_authenticator.py
test/unit/test_crypto_wrapping_keys.py
test/unit/test_material_managers_caching.py
test_vector_handlers/setup.py

Primarily some pylint ignores for things we don't care about in setup or test files.
Also fixes a bunch of pylint fixture deprecation warnings. Previously we had ~60 of these:
```
test/unit/test_material_managers_caching.py:391
/Users/farleyb/workspace/esdk/python/aws-encryption-sdk-python/test/unit/test_material_managers_caching.py:391:
PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
Use @pytest.fixture instead; they are the same.
```

chore: Fix CI

---

CHANGELOG.rst
SUPPORT_POLICY.rst
src/aws_encryption_sdk/identifiers.py

Table updated: https://github.com/farleyb-amazon/aws-encryption-sdk-python/blob/release-3.0/SUPPORT_POLICY.rst
Changelog updated: https://github.com/farleyb-amazon/aws-encryption-sdk-python/blob/release-3.0/CHANGELOG.rst

chore: Prep for release 3.0.0

---

buildspec.yml
codebuild/py310/awses_local.yml
codebuild/py310/examples.yml
codebuild/py310/integ.yml
test_vector_handlers/tox.ini
tox.ini

- Add Python 3.10 to tox
- Add Python 3.10 testing to CodeBuild

ci(py310): test against python3.10.0

---

src/aws_encryption_sdk/__init__.py
src/aws_encryption_sdk/compatability.py
src/aws_encryption_sdk/streaming_client.py
test/pylintrc
test/unit/test_compatability.py

*Issue #, if available:* Check Python Runtime
*Description of changes:* Implements A runtime check on the Python Version.
Runtime Check:
- Issues a WARNING if the Python Version will become/is unsupported.
- Will start issuing WARNING for Python Version less than 3.6.

feat(compatability): Check Python Runtime

---

.readthedocs.yaml
doc/requirements.txt

Fix RTD config to point to correct requirements. Also pin dependencies so we have reproducible builds.
See failing builds here: https://readthedocs.org/projects/aws-encryption-sdk-python/builds/15218410/
And known issue here: https://github.yuuza.net/sphinx-doc/sphinx/issues/9727
*Testing:*
I couldn't precisely reproduce this issue because it seems to be specific to how RTD configures its environment (in our case, pulling in a sphinx dependency < 2). That said, when I locally run the sphinx build to create docs (which specifies sphinx>1.3.0) it succeeds.

chore: update readthedocs config

---

codebuild/release/validate.yml
tox.ini

ci: Fix park and Validate

---

doc/conf.py

Turns out when we moved to a newer version of sphinx (https://github.com/aws/aws-encryption-sdk-python/pull/374) it changed how we need to specify config options.
See also: https://github.com/aws/aws-dynamodb-encryption-python/pull/191
*Testing:*
`tox -e serve-docs` shows me the full API docs.

chore: fix generated docs

---

MANIFEST.in

*Issue #, if available:* Downloads from PyPi do not include the JSON files needed for testing.
*Description of changes:* Add JSON file pattern under `test/` to manifest.

fix(MANIFEST): add testing resources

---

examples/src/basic_encryption.py
test/unit/test_encryption_context.py

https://github.com/aws/aws-encryption-sdk-python/issues/259
Clarify that key ARNs are required when trying to decrypt using
a StrictKMSMasterKeyProvider

chore: update example wording

---

.readthedocs.yaml

Didn't catch this necessary update after moving requirements.txt files around. This fixes our docs buld.

chore: Fix docs

---

dev_requirements/linter-requirements.txt
test/unit/test_encryption_context.py
tox.ini

Pin dependencies for linters to minimize broken builds on old branch

chore: Pin dependencies for linters

---

dev_requirements/linter-requirements.txt
test/unit/test_encryption_context.py
tox.ini

chore: Pin linter dependencies

---

.github/dependabot.yml

chore: remove dependabot from old branches

---

.github/workflows/dependabot-auto-merge.yml

*Description of changes:* This PR adds an Actions workflow to automatically merge dependabot patch-update PRs once they are approved, [as described in the GitHub docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request).
Because we require code-owner approval to merge PRs, new dependabot PRs still require human interaction before they are merged. This is intentional as it lets us ensure that the automatic merge works as desired. We can later set up another [Actions workflow to automatically approve dependabot PRs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automa …

ci: auto-merge dependabot patch update PRs

---

.github/workflows/dependabot-auto-merge.yml

*Description of changes:* The dependabot auto-merge workflow introduced by #431 doesn't work because I left in the example condition that the dependency name must be `my-dependency` (oops). This PR removes that condition.

ci: fix dependabot auto-merge condition

---

src/aws_encryption_sdk/internal/crypto/authentication.py
src/aws_encryption_sdk/internal/crypto/elliptic_curve.py
test/unit/test_crypto_authentication_signer.py
test/unit/test_crypto_authentication_verifier.py
test/unit/test_crypto_elliptic_curve.py
test/unit/test_crypto_prehashing_authenticator.py
test_vector_handlers/src/pylintrc
test_vector_handlers/tox.ini

#464
1. `pyca/cryptography` is planning to remove `verify_interface`. However; since they run the esdk as downstream in ci, they can't deprecate the function without breaking their CI. This PR is intended to unblock them by removing `verify_interface` from the ESDK. `verify_interface` takes an abstract class in this case `ec.EllipticCurve` and the subclass object you wish to verify, in our use case it's `algorithm.signing_algorithm_info` which is a subclass that implements the `ec.EllipticCurve` abstract class. The only allowed subclasses we use are `ec.SECP256R1` and `ec.SECP384R1`  and `verify_interface` goes through the class and makes sure that the expected values are there. Since both of the allowed subclasses implement …

refactor: replace verify_interface with isinstance

---

codebuild/release/prod-release.yml
codebuild/release/test-release.yml

When executing the codebuild, it drops you in the `master`branch if we want to release from separate branch we need to first checkout that branch. We do this in the Java ESDK and works great.

chore: checkout corresponding branch instead of commit

---

src/aws_encryption_sdk/streaming_client.py

Similar logging is classified at DEBUG level. There is also no value added to a functioning implementation as the log statements just help document stepping through lines, which in my opinion is a debugging activity. There is no 'INFO' being added by these noisy log statements.

refactor: reduce logging verbosity

---

CHANGELOG.rst
SUPPORT_POLICY.rst
src/aws_encryption_sdk/__init__.py
src/aws_encryption_sdk/identifiers.py

*Issue #, if available:* Mark 1.x as End-of-Support
- ESDK-Python emits a Deprecation warning on creation detailing 1.x is in End-of-Support
- Added the support policy from master
- updated the support policy from master to mark 1.x & 2.x as End-of-Support.

chore: Mark 1.x as End-of-Support

---

CHANGELOG.rst
SUPPORT_POLICY.rst
src/aws_encryption_sdk/__init__.py
src/aws_encryption_sdk/identifiers.py
tox.ini

*Issue #, if available:* Mark 1.x as End-of-Support
- ESDK-Python emits a Deprecation warning on creation detailing 2.x is in End-of-Support
- Added the support policy from master
- updated the support policy from master to mark 1.x & 2.x as End-of-Support.

chore: Mark 2.x as End-of-Support

---

codebuild/release/test-release.yml
decrypt_oracle/test/pylintrc

Uses API token instead of username and password to publish artifacts to TestPyPi. Token only has access to publish you cannot log into the account with it.

chore(release): add api token to staging release process

---

codebuild/release/prod-release.yml

Use API token to upload to pypi instead of username and password.

chore(release): add api token to prod release process

---

decrypt_oracle/test/integration/test_i_decrypt_oracle.py
decrypt_oracle/tox.ini
src/aws_encryption_sdk/__init__.py
tox.ini

*Issue #, if available:* [Failing lint check](https://github.com/aws/aws-encryption-sdk-python/runs/8081967632?check_suite_focus=true)
- Add timeout of 2 minutes to call
- Pin linting dependencies

chore: address linter concern

---

decrypt_oracle/test/integration/test_i_decrypt_oracle.py
decrypt_oracle/tox.ini
requirements.txt

*Issue #, if available:* [#307](https://github.com/aws/aws-encryption-sdk-cli/issues/307)
*Description of changes:* 
- Update `cryptography` dependency range.
*Testing*:
I tested every Major Pyca since 2.5.0 explicitly via:
1. `sed -i.backup 's/cryptography>=2.5.0/cryptography==$PYCA/g' requirements.txt`
2. `tox -e py38-integ -r`
3. `git restore requirements.txt`
Where PYCA is one of `[2.5.0, 3.0.*, 3.2.*, 3.3.*, 35.*, 36.*, 37.*, 3.4.*]`.
Only 37 failed.

fix: update pyca range

---

codebuild/release/prod-release.yml
codebuild/release/test-release.yml

Use API token as creds to log in to TestPyPi and PyPi instead of username and password

chore(release): add api token to staging and  prod release process

---

codebuild/release/prod-release.yml
codebuild/release/test-release.yml

Use API Token for TestPyPi and PyPi instead of usesrname and password.

chore(release): add api token to staging and prod release process

---

CHANGELOG.rst

*Issue #, if available:* 
Update CHANGELOG for 2.5.1 release.
Note:
While `cryptography==3.3.2` was the last to support Python2.7,
`pip` is clever enough to use `3.3.2` on Python2.7 and the latest available for other Pythons.

chore: changelog

---

codebuild/coverage/coverage.yml
codebuild/py310/awses_local.yml
codebuild/py310/examples.yml
codebuild/py310/integ.yml
codebuild/py37/awses_local.yml
codebuild/py37/examples.yml
codebuild/py37/integ.yml
codebuild/py38/awses_local.yml
codebuild/py38/examples.yml
codebuild/py38/integ.yml
codebuild/py39/awses_1.7.1.yml
codebuild/py39/awses_2.0.0.yml
codebuild/py39/awses_latest.yml
codebuild/py39/examples.yml
codebuild/py39/integ.yml
codebuild/release/prod-release.yml
codebuild/release/test-release.yml
codebuild/release/validate.yml
decrypt_oracle/src/aws_encryption_sdk_decrypt_oracle/app.py

fix: Updates the decrypt oracle commitment policy to `FORBID_ENCRYPT_ALLOW_DECRYPT` to be backwards compatible.
*Testing*
Deployed and tested on dev account

fix: Use FORBID_ENCRYPT_ALLOW_DECRYPT policy for decrypt oracle

---

.github/workflows/ci_tests.yaml
test/upstream-requirements-py311.txt
tox.ini

*Issue #, if available:* https://github.com/pyca/cryptography/pull/8115
*Description of changes:* 
- Explicitly test Python 3.10 & Python 3.11 in CI.
- Update Freeze Dependencies for Python 3.7
- Add Freeze Dependencies for Python 3.11

chore: freeze py311 depedencies for pyca and test in CI

---

src/aws_encryption_sdk/compatability.py

*Issue #545 :*
Swapped `minimum_version` and `date` as described in issue solution

fix: wrong formatting python warning (#545)

---

decrypt_oracle/.chalice/pipeline.py
decrypt_oracle/src/pylintrc

This commit fixes the pylint issue for the decrypt_oracle. This has been tested on a personal account.

fix: CI for Decrypt Oracle

---

test/functional/test_f_crypto.py

It takes a curve instance, not a curve class

fix(test): correctly invoke ec.generate_private_key

---

.github/workflows/ci_static-analysis.yaml
.github/workflows/ci_test-vector-handler.yaml
.github/workflows/ci_tests.yaml
buildspec.yml
codebuild/py310/awses_local.yml
codebuild/py310/examples.yml
codebuild/py310/integ.yml
codebuild/py311/awses_local.yml
codebuild/py311/examples.yml
codebuild/py311/integ.yml
codebuild/py312/awses_local.yml
codebuild/py312/examples.yml
codebuild/py312/integ.yml
codebuild/py37/awses_local.yml
codebuild/py37/examples.yml
codebuild/py37/integ.yml
codebuild/py38/awses_local.yml
codebuild/py38/examples.yml
codebuild/py38/integ.yml
codebuild/py39/awses_1.7.1.yml
codebuild/py39/awses_2.0.0.yml
codebuild/py39/awses_latest.yml
codebuild/py39/examples.yml
codebuild/py39/integ.yml
dev_requirements/ci-requirements.txt
test/unit/test_caches_base.py
test/unit/test_material_managers_base.py
tox.ini

*Issue #, if available:* Test Python 3.12 in CI.

feat: test Python 3.12 in CI

---

codebuild/py312/awses_local.yml
codebuild/py312/examples.yml
codebuild/py312/integ.yml
codebuild/release/validate.yml

- codebuild ci is failing with `pyenv 3.12.0 already exists`, with this change ci will skip `pyenv` installation if already exists

chore: skip pyenv installation if already exists

---

README.rst
requirements.txt

*Issue #, if available:* #625
bump required version of cryptography from 3.6.0. to 3.6.4, for consistency with other libraries.
update required version of cryptography mentioned in README to match

feat: update requirements and README

---

CHANGELOG.rst
src/aws_encryption_sdk/identifiers.py

chore: update changelog and identifiers.py

---

cfn/ESDK-Python.yml

chore(CFN): Changes for TestVectors

---

src/aws_encryption_sdk/internal/crypto/wrapping_keys.py

Catch a `ValueError` thrown by cryptography if the master key provider cannot decrypt the EDK, and surface it as a `IncorrectMasterKeyError`.
From MKP Decrypt Data Key [spec](https://github.com/awslabs/aws-encryption-sdk-specification/blob/ceef8726ee79084aaabfd93e7e18d9f3f07f7420/framework/master-key-provider-interface.md):
"The master key provider SHOULD attempt to decrypt the data key by passing the request to any master keys that it has access to until it has either exhausted available master keys or obtained a plaintext data key."
Surfacing the `ValueError` as an `IncorrectMasterKeyError` lets [this logic](https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/key_providers/base.py#L300) swallow the …

fix: Handle errors when decrypting multiple EDKs with raw RSA MKPs

---

examples/src/keyrings/aws_kms_mrk_keyring_example.py
examples/src/keyrings/aws_kms_mrk_multi_keyring_example.py
examples/test/keyrings/test_i_aws_kms_mrk_keyring_example.py
examples/test/keyrings/test_i_aws_kms_mrk_multi_keyring_example.py

chore(examples): Added mrk and mrk_multi keyring examples

---

CHANGELOG.rst
src/aws_encryption_sdk/identifiers.py

chore(release): update changelog and identifiers.py for v3.3.0

chore(release): update changelog and identifiers.py

---

.readthedocs.yaml

Fix for docs failing issue for ESDK-python

fix(.readthedocs.yaml): fix docs failing issue

---

cfn/ESDK-Python.yml

*Issue #, if available:* n/a
*Description of changes:* updates the CFN template to include the "new" PyPi secrets which move us to API token. this was manually changed in the account for the previous release, but not reflected in CFN. there are some other changes which I am not attempting to fix until we run a release, so as to avoid breaking our release. 

chore: add PyPi API tokens to Cfn template

---

examples/src/aws_kms_discovery_keyring_example.py
examples/src/aws_kms_discovery_multi_keyring_example.py
examples/src/aws_kms_keyring_example.py
examples/src/aws_kms_mrk_discovery_keyring_example.py
examples/src/aws_kms_mrk_discovery_multi_keyring_example.py
examples/src/aws_kms_mrk_keyring_example.py
examples/src/aws_kms_mrk_multi_keyring_example.py
examples/src/aws_kms_multi_keyring_example.py
examples/src/aws_kms_rsa_keyring_example.py
examples/src/default_cryptographic_materials_manager_example.py
examples/src/file_streaming_example.py
examples/src/hierarchical_keyring_example.py
examples/src/migration/migration_aws_kms_key_example.py
examples/src/migration/migration_raw_aes_key_example.py
examples/src/migration/migration_raw_rsa_key_example.py
examples/src/migration/migration_set_commitment_policy_example.py
examples/src/multi_keyring_example.py
examples/src/multithreading/__init__.py
examples/src/raw_aes_keyring_example.py
examples/src/raw_rsa_keyring_example.py
examples/src/set_encryption_algorithm_suite_example.py

fix(Examples): Validate EC on decrypt

---

decrypt_oracle/.chalice/pipeline.py

Somehow, the oracle linter stopped working.
See CI for a commit that makes no changes to the repo: [link](https://github.com/aws/aws-encryption-sdk-python/actions/runs/11150896553/job/30993110138)
Let's ignore this linter failure -- we haven't touched this in years and almost certainly will put significant dev work into this again, so I'd rather not refactor this.

fix(CI): Fix oracle linting

---

examples/src/aws_kms_discovery_keyring_example.py
examples/src/aws_kms_discovery_multi_keyring_example.py
examples/src/aws_kms_keyring_example.py
examples/src/aws_kms_mrk_discovery_keyring_example.py
examples/src/aws_kms_mrk_discovery_multi_keyring_example.py
examples/src/aws_kms_mrk_keyring_example.py
examples/src/aws_kms_mrk_multi_keyring_example.py
examples/src/aws_kms_rsa_keyring_example.py
examples/src/default_cryptographic_materials_manager_example.py
examples/src/file_streaming_example.py
examples/src/migration/migration_set_commitment_policy_example.py
examples/src/raw_aes_keyring_example.py
examples/src/raw_rsa_keyring_example.py
examples/src/set_encryption_algorithm_suite_example.py

We removed code that explicitly checked "Encryption context is correct in the decrypted message header", and now recommend providing encryption context directly on decrypt. Removing this statement from all examples.

chore(examples): fix comments

---

src/aws_encryption_sdk/key_providers/base.py
test_vector_handlers/src/awses_test_vectors/manifests/master_key.py

fix: MKPs attempt to decrypt with remaining keys if a preceding raw RSA key failed to decrypt

---

README.rst
performance_tests/README.rst
performance_tests/requirements_mpl.txt
requirements_mpl.txt
setup.py

chore: Point at PyPI MPL

---

test_vector_handlers/src/awses_test_vectors/manifests/full_message/decrypt.py

Fix a timeout in TestVectors by removing redundant test scenarios.
CodeBuild CI has tests that decrypt generated vectors with both keyrings and MKPs.
However, the keyrings step actually decrypts with *both* keyrings and MKPs.
This change removes the MKP decryption from the keyrings step, since it is redundant.
This change fixes a timeout in CodeBuild CI.
CodeBuild CI times out after 60 minutes.
Before this change, CI would time out at roughly 60 minutes, but would sometimes succeed.

chore(CI): Fix TestVectors timeout

---

buildspec.yml
codebuild/py311/decrypt_golden_manifest_with_keyrings.yml
codebuild/py311/decrypt_golden_manifest_with_masterkey.yml
codebuild/py312/decrypt_golden_manifest_with_keyrings.yml
codebuild/py312/decrypt_golden_manifest_with_masterkey.yml
test_vector_handlers/src/awses_test_vectors/manifests/full_message/decrypt.py
test_vector_handlers/src/awses_test_vectors/manifests/mpl_keyring.py

feat(TestVectors): Decrypt "golden" manifest

---

.github/workflows/ci_test-vector-handler.yaml
.github/workflows/ci_tests.yaml

chore(CI): Bump from macOS 12 to 13

---

.github/workflows/ci_codebuild-tests.yml

The CodeBuild CI change I deployed yesterday takes 55-60 minutes and times out at 60 minutes.
Bump the timeout slightly to prevent flaky CI.

chore: Increase timeout for CodeBuild CI

---

dev_requirements/release-requirements.txt

`twine` needs a MV bump since the last ESDK-Python release.
ESDK-Python 4.0.0 release failed with the errors described in https://github.com/astral-sh/rye/issues/1180
One solution described there is to bump `twine`.
This PR bumps `twine` to `5.1.1` (same version used by MPL-Python).

chore(deps-release): bump twine from 4.0.1 to 5.1.1

---

SUPPORT_POLICY.rst
test_vector_handlers/src/awses_test_vectors/internal/mpl/tampering_mpl_materials.py

chore: Update release policy, fix linter

---

.github/workflows/ci_codebuild-tests.yml
.github/workflows/ci_codebuild_batch.yml
.github/workflows/ci_decrypt-oracle.yaml
.github/workflows/ci_static-analysis.yaml
.github/workflows/ci_test-vector-handler.yaml
.github/workflows/ci_tests.yaml
.github/workflows/daily_ci.yml
.github/workflows/pull.yml
.github/workflows/push.yml

chore(CI): clean up gha and unused files
