aws/aws-encryption-sdk-python

MANIFEST.in
adding docs, tests, and examples to MANIFEST.in to include those in sdist
=> adding docs, tests, and examples to MANIFEST.in to include those in sdist

.github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, NOTICE
Adding the stock AWS contributing/code of conduct files.
=> Adding contributing docs

park.cfg, tox.ini
Finally remembering to add PyPI typosquatting to this package.
=> Typosquatting

CHANGELOG.rst, CONTRIBUTING.md, README.rst, setup.py, src/aws_encryption_sdk/identifiers.py
*Issue #, if available:* n/a
*Description of changes:* Documentation changes to update hyperlinks, and minor version bump.
=> Move repository from awslabs to aws.

test/unit/test_defaults.py
*Issue #, if available:* #99 
Migrated "test/unit/test_defaults.py " from unittest to pytest
=> Migrate unit/test_defaults.py from unittest to pytest

.travis.yml, decrypt_oracle/.chalice/pipeline.py, decrypt_oracle/app.py, decrypt_oracle/setup.cfg, decrypt_oracle/src/aws_encryption_sdk_decrypt_oracle/app.py, decrypt_oracle/src/aws_encryption_sdk_decrypt_oracle/key_providers/counting.py, decrypt_oracle/src/aws_encryption_sdk_decrypt_oracle/key_providers/null.py, decrypt_oracle/src/pylintrc, decrypt_oracle/test/pylintrc, decrypt_oracle/tox.ini
Clean up linting issues in decrypt oracle and enable linting checks in CI.
=> Decrypt oracle linting

src/aws_encryption_sdk/key_providers/kms.py, src/aws_encryption_sdk/materials_managers/caching.py
=> Remove unused variable assignments

src/aws_encryption_sdk/identifiers.py, src/aws_encryption_sdk/internal/formatting/deserialize.py
Apparently flake8 checks type annotations now.
=> add typing imports

examples/src/data_key_caching_basic.py
=> Tweak example text

src/aws_encryption_sdk/materials_managers/base.py, src/aws_encryption_sdk/materials_managers/caching.py, src/aws_encryption_sdk/materials_managers/default.py
*Issue #, if available:* n/a
*Description of changes:* Spotted a couple of typos while rereading the code and thought I would tidy up.
=> Fix small doc typos.

test/functional/key_providers/test_base.py, test/functional/test_f_aws_encryption_sdk_client.py
It would appear that I need to check our CI...I thought we had something that would have caught this. :/
=> apply autoformatting

CHANGELOG.rst, src/aws_encryption_sdk/identifiers.py
Update changelog and bump version to 1.4.1 for release today.
=> 1.4.1 release

CHANGELOG.rst
=> docs: add mention of new examples to changelog

examples/src/crypto_materials_manager/caching/simple_cache.py, examples/src/crypto_materials_manager/custom/algorithm_suite_enforcement.py, examples/src/crypto_materials_manager/custom/requiring_encryption_context_fields.py, examples/src/file_streaming_defaults.py, examples/src/in_memory_streaming_defaults.py, examples/src/keyring/aws_kms/act_like_aws_kms_master_key_provider.py, examples/src/keyring/aws_kms/custom_client_supplier.py, examples/src/keyring/aws_kms/custom_kms_client_config.py, examples/src/keyring/aws_kms/discovery_decrypt.py, examples/src/keyring/aws_kms/discovery_decrypt_in_region_only.py, examples/src/keyring/aws_kms/discovery_decrypt_with_preferred_regions.py, examples/src/keyring/aws_kms/multiple_regions.py, examples/src/keyring/aws_kms/single_cmk.py, examples/src/keyring/multi/aws_kms_with_escrow.py, examples/src/keyring/raw_aes/raw_aes.py, examples/src/keyring/raw_rsa/keypair.py, examples/src/keyring/raw_rsa/keypair_from_pem.py, examples/src/keyring/raw_rsa/public_private_key_separate.py, examples/src/master_key_provider/aws_kms/discovery_decrypt.py, examples/src/master_key_provider/aws_kms/multiple_regions.py, examples/src/master_key_provider/aws_kms/single_cmk.py, examples/src/master_key_provider/multi/aws_kms_with_escrow.py, examples/src/master_key_provider/raw_aes/raw_aes.py, examples/src/master_key_provider/raw_rsa/private_key_only_from_pem.py, examples/src/onestep_defaults.py, examples/src/onestep_unsigned.py
@MatthewBennington suggested this and I like it. We can't be too redundant about this. :)
=> docs: add note in every example pointing out that encryption context is not secret

src/aws_encryption_sdk/keyrings/aws_kms/__init__.py, test/unit/caches/test_local.py
*Issue #, if available:* N/A
*Description of changes:* Specify the type of a sentinel passed during tests.
=> fix: get CI passing again

test/unit/test_caches_local.py
Pulling in @MatthewBennington's changes from #288 to make CI stop yelling at me.
=> fix: get CI passing again (#288)

CHANGELOG.rst, src/aws_encryption_sdk/identifiers.py
=> Update version identifier to 1.7.1

.github/workflows/repo-sync.yml
See https://github.com/repo-sync/repo-sync
=> chore: Add repo-sync action to pull updates from the public repo

README.rst, SUPPORT_POLICY.rst
Add a dedicated page describing our support policy, and link to it from the README.
https://github.com/farleyb-amazon/aws-encryption-sdk-python/blob/support-policy/SUPPORT_POLICY.rst
=> chore: Add support policy

CHANGELOG.rst, README.rst
=> chore: Update changelog and readme for 2.4.0

src/aws_encryption_sdk/identifiers.py
=> chore: Update version to 2.4.0

.github/workflows/ci_decrypt-oracle.yaml, .github/workflows/ci_static-analysis.yaml, .github/workflows/ci_test-vector-handler.yaml, .github/workflows/ci_tests.yaml, codebuild/py35/awses_local.yml, codebuild/py35/examples.yml, codebuild/py35/integ.yml, codebuild/py36/awses_local.yml, codebuild/py36/examples.yml, codebuild/py36/integ.yml, codebuild/py37/awses_local.yml, codebuild/py37/examples.yml, codebuild/py37/integ.yml, codebuild/py38/awses_local.yml, codebuild/py38/examples.yml, codebuild/py38/integ.yml, codebuild/py39/awses_1.7.1.yml, codebuild/py39/awses_2.0.0.yml, codebuild/py39/awses_latest.yml, codebuild/py39/examples.yml, codebuild/py39/integ.yml, decrypt_oracle/src/pylintrc, decrypt_oracle/test/pylintrc, examples/src/pylintrc, examples/test/pylintrc, src/pylintrc, test/pylintrc, test_vector_handlers/src/pylintrc, test_vector_handlers/test/pylintrc
*Issue #, if available:* Update Minor Python versions used for testing.
- In CodeBuild, use the latest release of Python Minor versions as of 2021-11-08
- In GitHub, use the latest version of `actions/setup-python`
- For all pylint environments, ignore fstring recommendations.
=> ci: Update CI

CHANGELOG.rst, src/aws_encryption_sdk/identifiers.py
*Issue #, if available:* CHANGELOG and Version bump for 3.1.0 release
=> chore: Changelog for 3.1 release

codebuild/release/validate.yml
=> fix(CodeBuild): pyenv local before pip installing

tox.ini
=> 2.x dep fixup

dev_requirements/linter-requirements.txt
=> chore(deps): update black dependency

CHANGELOG.rst, src/aws_encryption_sdk/identifiers.py
=> chore: changelog for 3.1.1 release

CHANGELOG.rst, src/aws_encryption_sdk/identifiers.py
=> chore: changelog for 2.5.0 release

SUPPORT_POLICY.rst
*Issue #, if available:* Mark 1.x & 2.x as End-of-Support
- Update Support Policy, marking 1.x & 2.x as End-of-Support
=> docs(SupportPolicy): Mark 1.x & 2.x End-of-Support

cfn/ESDK-Python.yml
This commits the CFN as it exists today.
=> chore(CFN): Commit existing CFN

src/aws_encryption_sdk/__init__.py
Updated description of decrypt() usage
=> chore: Updated description of decrypt() usage in src/aws_encryption_sdk/__init__.py

.github/workflows/ci_test-vector-handler.yaml, .github/workflows/ci_tests.yaml
Changed macos-latest to macos-12
=> fix(CI): updated ci_test-vector-handler.yaml and ci_tests.yaml

README.rst, performance_tests/README.rst, performance_tests/requirements_mpl.txt, requirements_mpl.txt, setup.py
=> chore: Bump to MPL 1.7.4
